//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalkanAir.Web.Account {
    
    
    public partial class Settings {
        
        /// <summary>
        /// IsEmailConfirmedLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal IsEmailConfirmedLiteral;
        
        /// <summary>
        /// SendConfirmationEmailLinkButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton SendConfirmationEmailLinkButton;
        
        /// <summary>
        /// ReceiveEmailWhenNewNewsCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox ReceiveEmailWhenNewNewsCheckBox;
        
        /// <summary>
        /// ReceiveEmailWhenNewFlightCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox ReceiveEmailWhenNewFlightCheckBox;
        
        /// <summary>
        /// ReceiveNotificationWhenNewNewsCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox ReceiveNotificationWhenNewNewsCheckBox;
        
        /// <summary>
        /// ReceiveNotificationWhenNewFlightCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox ReceiveNotificationWhenNewFlightCheckBox;
        
        /// <summary>
        /// SaveSettingsBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button SaveSettingsBtn;
    }
}
