//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalkanAir.Web.Booking {
    
    
    public partial class Extras {
        
        /// <summary>
        /// OneWayRouteBabyEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox OneWayRouteBabyEquipmentCheckBox;
        
        /// <summary>
        /// OneWayRouteSportsEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox OneWayRouteSportsEquipmentCheckBox;
        
        /// <summary>
        /// OneWayRouteMusicEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox OneWayRouteMusicEquipmentCheckBox;
        
        /// <summary>
        /// OneWayRouteSelectSeatBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button OneWayRouteSelectSeatBtn;
        
        /// <summary>
        /// OneWayRouteSelectedSeatImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image OneWayRouteSelectedSeatImage;
        
        /// <summary>
        /// OneWayRouteSelectedSeatLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OneWayRouteSelectedSeatLabel;
        
        /// <summary>
        /// ReturnRouteExtrasPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ReturnRouteExtrasPanel;
        
        /// <summary>
        /// ReturnRouteBabyEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ReturnRouteBabyEquipmentCheckBox;
        
        /// <summary>
        /// ReturnRouteSportsEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ReturnRouteSportsEquipmentCheckBox;
        
        /// <summary>
        /// ReturnRouteMusicEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ReturnRouteMusicEquipmentCheckBox;
        
        /// <summary>
        /// ReturnRouteSelectSeatBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ReturnRouteSelectSeatBtn;
        
        /// <summary>
        /// ReturnRouteSelectedSeatImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image ReturnRouteSelectedSeatImage;
        
        /// <summary>
        /// ReturnRouteSelectedSeatLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnRouteSelectedSeatLabel;
        
        /// <summary>
        /// ContinueBookingBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ContinueBookingBtn;
        
        /// <summary>
        /// OneWayRouteSelectedCheckedInBagPriceHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteSelectedCheckedInBagPriceHiddenField;
        
        /// <summary>
        /// OneWayRouteSelectedCheckedInBagWeightHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteSelectedCheckedInBagWeightHiddenField;
        
        /// <summary>
        /// OneWayRouteNumberOfCheckedInBagsHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteNumberOfCheckedInBagsHiddenField;
        
        /// <summary>
        /// OneWayRouteSelectedCabinBagPriceHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteSelectedCabinBagPriceHiddenField;
        
        /// <summary>
        /// OneWayRouteSelectedCabinBagSizeHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteSelectedCabinBagSizeHiddenField;
        
        /// <summary>
        /// ReturnRouteSelectedCheckedInBagPriceHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteSelectedCheckedInBagPriceHiddenField;
        
        /// <summary>
        /// ReturnRouteSelectedCheckedInBagWeightHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteSelectedCheckedInBagWeightHiddenField;
        
        /// <summary>
        /// ReturnRouteNumberOfCheckedInBagsHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteNumberOfCheckedInBagsHiddenField;
        
        /// <summary>
        /// ReturnRouteSelectedCabinBagPriceHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteSelectedCabinBagPriceHiddenField;
        
        /// <summary>
        /// ReturnRouteSelectedCabinBagSizeHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteSelectedCabinBagSizeHiddenField;
    }
}
