//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalkanAir.Web.Booking {
    
    
    public partial class Extras {
        
        /// <summary>
        /// OneWayRouteExtrasPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel OneWayRouteExtrasPanel;
        
        /// <summary>
        /// OneWayRouteCheckedInBaggagePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel OneWayRouteCheckedInBaggagePanel;
        
        /// <summary>
        /// OneWayRouteNoneCheckedInBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton OneWayRouteNoneCheckedInBag;
        
        /// <summary>
        /// OneWayRoute23KgCheckedInBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton OneWayRoute23KgCheckedInBag;
        
        /// <summary>
        /// OneWayRoute32KgCheckedInBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton OneWayRoute32KgCheckedInBag;
        
        /// <summary>
        /// OneWayRouteCabinBaggagePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel OneWayRouteCabinBaggagePanel;
        
        /// <summary>
        /// OneWayRouteSmallCabinBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton OneWayRouteSmallCabinBag;
        
        /// <summary>
        /// OneWayRouteLargeCabinBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton OneWayRouteLargeCabinBag;
        
        /// <summary>
        /// OneWayRouteOtherBaggagePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel OneWayRouteOtherBaggagePanel;
        
        /// <summary>
        /// OneWayRouteBabyEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox OneWayRouteBabyEquipmentCheckBox;
        
        /// <summary>
        /// OneWayRouteSportsEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox OneWayRouteSportsEquipmentCheckBox;
        
        /// <summary>
        /// OneWayRouteMusicEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox OneWayRouteMusicEquipmentCheckBox;
        
        /// <summary>
        /// OneWayRouteSelectSeatBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button OneWayRouteSelectSeatBtn;
        
        /// <summary>
        /// OneWayRouteSelectedSeatImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image OneWayRouteSelectedSeatImage;
        
        /// <summary>
        /// OneWayRouteSelectedSeatLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OneWayRouteSelectedSeatLabel;
        
        /// <summary>
        /// ReturnRouteExtrasPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ReturnRouteExtrasPanel;
        
        /// <summary>
        /// ReturnRouteCheckedInBaggagePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ReturnRouteCheckedInBaggagePanel;
        
        /// <summary>
        /// ReturnRouteNoneCheckedInBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton ReturnRouteNoneCheckedInBag;
        
        /// <summary>
        /// ReturnRoute23KgCheckedInBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton ReturnRoute23KgCheckedInBag;
        
        /// <summary>
        /// ReturnRoute32KgCheckedInBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton ReturnRoute32KgCheckedInBag;
        
        /// <summary>
        /// ReturnRouteCabinBaggagePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ReturnRouteCabinBaggagePanel;
        
        /// <summary>
        /// ReturnRouteSmallCabinBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton ReturnRouteSmallCabinBag;
        
        /// <summary>
        /// ReturnRouteLargeCabinBag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton ReturnRouteLargeCabinBag;
        
        /// <summary>
        /// ReturnRouteOtherBaggagePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ReturnRouteOtherBaggagePanel;
        
        /// <summary>
        /// ReturnRouteBabyEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ReturnRouteBabyEquipmentCheckBox;
        
        /// <summary>
        /// ReturnRouteSportsEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ReturnRouteSportsEquipmentCheckBox;
        
        /// <summary>
        /// ReturnRouteMusicEquipmentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ReturnRouteMusicEquipmentCheckBox;
        
        /// <summary>
        /// ReturnRouteSelectSeatBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ReturnRouteSelectSeatBtn;
        
        /// <summary>
        /// ReturnRouteSelectedSeatImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image ReturnRouteSelectedSeatImage;
        
        /// <summary>
        /// ReturnRouteSelectedSeatLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ReturnRouteSelectedSeatLabel;
        
        /// <summary>
        /// ContinueBookingBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ContinueBookingBtn;
        
        /// <summary>
        /// OneWayRouteNumberOfCheckedInBagsHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteNumberOfCheckedInBagsHiddenField;
        
        /// <summary>
        /// ReturnRouteNumberOfCheckedInBagsHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteNumberOfCheckedInBagsHiddenField;
    }
}
