//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalkanAir.Web.Booking {
    
    
    public partial class SelectFlight {
        
        /// <summary>
        /// OneWayRouteTravelClassCustomValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CustomValidator OneWayRouteTravelClassCustomValidator;
        
        /// <summary>
        /// ReturnRouteTravelClassCustomValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CustomValidator ReturnRouteTravelClassCustomValidator;
        
        /// <summary>
        /// InvalidArrivalDateCustomValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CustomValidator InvalidArrivalDateCustomValidator;
        
        /// <summary>
        /// FlightDetailsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel FlightDetailsPanel;
        
        /// <summary>
        /// OneWayRouteDepartureDatesRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater OneWayRouteDepartureDatesRepeater;
        
        /// <summary>
        /// UP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UP;
        
        /// <summary>
        /// ShowOneWayFlgihtInfoHiddenButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ShowOneWayFlgihtInfoHiddenButton;
        
        /// <summary>
        /// OneWayFlightDetailsFormView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView OneWayFlightDetailsFormView;
        
        /// <summary>
        /// OneWayFlightTravelClassesRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater OneWayFlightTravelClassesRepeater;
        
        /// <summary>
        /// OneWayRouteInitialSlideIndexHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteInitialSlideIndexHiddenField;
        
        /// <summary>
        /// OneWayRouteCurrentFlightInfoIdHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteCurrentFlightInfoIdHiddenField;
        
        /// <summary>
        /// OneWayRouteSelectedFlightIdHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteSelectedFlightIdHiddenField;
        
        /// <summary>
        /// OneWayRouteSelectedTravelClassIdHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField OneWayRouteSelectedTravelClassIdHiddenField;
        
        /// <summary>
        /// ReturnRouteFlightsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ReturnRouteFlightsPanel;
        
        /// <summary>
        /// ReturnRouteDepartureDatesRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater ReturnRouteDepartureDatesRepeater;
        
        /// <summary>
        /// ShowReturnFlgihtInfoHiddenButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ShowReturnFlgihtInfoHiddenButton;
        
        /// <summary>
        /// ReturnFlightDetailsFormView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView ReturnFlightDetailsFormView;
        
        /// <summary>
        /// ReturnFlightTravelClassesRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater ReturnFlightTravelClassesRepeater;
        
        /// <summary>
        /// ReturnRouteInitialSlideIndexHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteInitialSlideIndexHiddenField;
        
        /// <summary>
        /// ReturnRouteCurrentFlightInfoIdHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteCurrentFlightInfoIdHiddenField;
        
        /// <summary>
        /// ReturnRouteSelectedFlightIdHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteSelectedFlightIdHiddenField;
        
        /// <summary>
        /// ReturnRouteSelectedTravelClassIdHiddenField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReturnRouteSelectedTravelClassIdHiddenField;
        
        /// <summary>
        /// ContinueBookingBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ContinueBookingBtn;
        
        /// <summary>
        /// SignInRequiredPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel SignInRequiredPanel;
        
        /// <summary>
        /// CreateNewAccountToContinueBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CreateNewAccountToContinueBtn;
        
        /// <summary>
        /// SignInToContinueBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button SignInToContinueBtn;
    }
}
